### ISSUE TITLE
Understanding get_dev_session_loader

### ISSUE THREAD

**Issue by emduc** [aSeriousCoder/DivHGNN#1]
Hey there ! 

Great project :) I am trying to play around with your MIND dataset to try out the model and maybe add some custom changes to it. I struggle with the function `get_dev_session_loader`. My understanding is that the Session data set should contain the positive and negative edges, however the self._dev_session_positive / self._dev_session_negative objects are arrays of **arrays of** positive / negative interactions. That means they cannot be used as edges directly, but the code seems to do so since they are given to the dataloader directly. When I try to reproduce that, I get an error complaining that the arrays in the loader are of different lengths. How is this supposed to work?

For me the dev_session_positive looks like:

> [[0, 1, 2], [3], [4, 5, 6, 7, 8], [9, 10], [11], ...]

I also found that the train_session_positive / negative are used in a different way. Is there something I am missing here? How can I test the model otherwise?

Is it possible the `SessionDataset` uploaded is not the final version?

On a sidenote if you used specific implementations as inspiration to implement your DGL MIND dataset, I would love if you could share that, to facilitate my trying outs. 💯 

Thanks a lot for your help, I would love to be able to reproduce your results!

**Comment by emduc** [comment]
after some more digging, I am wondering why there is a `SessionDataset` in the first place, shouldn't we use the same `building_training_dataset` method to create the test dev edges?

**Comment by aSeriousCoder** [comment]
Thank you very much for your attention to our project!

The raw data of the MIND dataset is organized by sessions. A session records a user's news recommendation interaction, which contains multiple news items. Some of these news items are clicked (a s positive news), while the rest are not clicked (as negative news).

Let's assume a session has M positive news and N negative news.

During model training, we use a fixed ratio of negative sampling (let's say K). Therefore, we process a session into M training samples, each containing one of the M positive news and K negative samples drawn from the N negative news. This part of the code can be found in `data.Utils.building_training_dataset`, as shown below:

```python
def building_training_dataset(session_positive, session_negative):
    sampled_datasets = []  # training edge dataset
    for i in range(len(session_positive)):
        pos_link = np.array(session_positive[i])
        neg_link = np.array(session_negative[i])
        len_pos = len(pos_link)
        len_neg = len(neg_link)
        # negative sampling to build training datasets
        for j in range(len_pos):
            if len_neg < hparams['gnn_neg_ratio']:
                nega_sample = []
                for s in range(int(hparams['gnn_neg_ratio'] / len_neg)):
                    nega_sample.append(neg_link)
                neg_sample_id = np.random.choice(len_neg, hparams['gnn_neg_ratio'] % len_neg, replace=False)
                nega_sample.append(neg_link[neg_sample_id])
                nega_sample = np.concatenate(nega_sample)
            else:
                neg_sample_id = np.random.choice(len_neg, hparams['gnn_neg_ratio'], replace=False)
                nega_sample = neg_link[neg_sample_id]
            sampled_datasets.append(np.concatenate([np.array([pos_link[j]]), nega_sample]))
    return np.array(sampled_datasets)
```

In validation and testing, we evaluate by sessions directly, so we use `data.MIND.SessionDataset` as the Dataset Class.

The rationale behind this design is that during training, we want the dimensions of the training data to be aligned for batch training. In contrast, during testing, we aim for a more realistic test scenario.

Hope this clarification can help you. 😎

**Comment by emduc** [comment]
Thanks a lot for your quick answer!

I now understand much better the evaluation part, this will save a lot of time :). My issue remains that the SessionDataset seems to simply not work on my side, because it take pos(/neg)_links to simply be self._dev_session_positive, and self._dev_session_positive are not edges, but should be processed into edges, am I wrong? Is the code working as is on your side?

**Comment by aSeriousCoder** [comment]
self._dev_session_positive and self._dev_session_negative contains the edge_ID of the corresponding edges, just as you mentioned before: 

> For me the dev_session_positive looks like:
> [[0, 1, 2], [3], [4, 5, 6, 7, 8], [9, 10], [11], ...]

Actually, when we perform the testing, we first encode all the users and news, and then scoring the user-news pairs along with these edges. As detailed information is preserved in the graph, we just need the IDs to retrieve these edges. 

You may find these codes in the main.full_eval and main.quick_eval (quick_eval tests on partal data for time saving):

```python
encode_all_graph(model, mind_dgl)
result = full_rec(model, mind_dgl, epoch, global_step)
# or
result = quick_rec(model, mind_dgl, epoch, global_step)
```

Which are different from the training process.

**Comment by emduc** [comment]
I found my mistake :) 
I increased the batch_size of the session loader which was set at 1. I can now use the model completely. 
Thanks a lot for your help, it was a stupid mistake but I understood much more of the system with your explanations. 👍
